
function getData(){
	const keysw = "www.mitreviews.com";
	var keyAPI = (typeof keyhost != 'undefined') ? keyhost : document.location.host;
	var dataAMZ = {};
	if(keysw == keyAPI){
		dataAMZ = {
			B08FPBV4VX: {href: "https://amzn.to/3uqW91R",nameProduct: ``,image: '',summary: ``,slug: ""},
			B0787BVSTH: {href: "https://amzn.to/3nWaxgq",nameProduct: ``,image: '',summary: ``,slug: ""},
			B07MHGVBLS: {href: "https://amzn.to/3ulb4L4",nameProduct: ``,image: '',summary: ``,slug: ""},
			B06XKDYD4S: {href: "https://amzn.to/3xTiXd1",nameProduct: ``,image: '',summary: ``,slug: ""},
			B00HHO0IEU: {href: "https://amzn.to/3vQL36R",nameProduct: ``,image: '',summary: ``,slug: ""},
			B00JJZBHK4: {href: "https://amzn.to/3b9tVBo",nameProduct: ``,image: '',summary: ``,slug: ""},
			B07B9TB8Q7: {href: "https://amzn.to/2Sry9O5",nameProduct: ``,image: '',summary: ``,slug: ""},
			B01ALBMIEI: {href: "https://amzn.to/3nXqSkL",nameProduct: ``,image: '',summary: ``,slug: ""},
			B01ICBLBL0: {href: "https://amzn.to/3up8nrP",nameProduct: ``,image: '',summary: ``,slug: ""},
			B06WGLM9V1: {href: "https://amzn.to/3eSmkYU",nameProduct: ``,image: '',summary: ``,slug: ""},
			B005RR0RDG: {href: "https://amzn.to/3nRQQGp",nameProduct: ``,image: '',summary: ``,slug: ""},
			B07MDG8MCH: {href: "https://amzn.to/3vNh67G",nameProduct: ``,image: '',summary: ``,slug: ""},
			B078HFRNPQ: {href: "https://amzn.to/3h662OX",nameProduct: ``,image: '',summary: ``,slug: ""},
			B07FPW5WXX: {href: "https://amzn.to/3uri1dt",nameProduct: ``,image: '',summary: ``,slug: ""},
			B019PBH9IA: {href: "https://amzn.to/3h2EEkN",nameProduct: ``,image: '',summary: ``,slug: ""},
			B08WYYNXKQ: {href: "https://amzn.to/2Rtrx1p",nameProduct: ``,image: '',summary: ``,slug: ""},
			B07TS69X9J: {href: "https://amzn.to/3nRhZt7",nameProduct: ``,image: '',summary: ``,slug: ""},
			B00K0NMFX2: {href: "https://amzn.to/2RqBrRg",nameProduct: ``,image: '',summary: ``,slug: ""},
			B079QYYGF1: {href: "https://amzn.to/3xRehnS",nameProduct: ``,image: '',summary: ``,slug: ""},
			B01D3FOIR4: {href: "https://amzn.to/3b9gXUd",nameProduct: ``,image: '',summary: ``,slug: ""},
			B07SFJXLYW: {href: "https://amzn.to/3vIZnhy",nameProduct: ``,image: '',summary: ``,slug: ""},
			B00N9IG28O: {href: "https://amzn.to/3tpTAvC",nameProduct: ``,image: '',summary: ``,slug: ""},
			B003YJAZZ4: {href: "https://amzn.to/3uq7yza",nameProduct: ``,image: '',summary: ``,slug: ""},
			B00A39FSAK: {href: "https://amzn.to/3eliPLo",nameProduct: ``,image: '',summary: ``,slug: ""},
			B01LA3VHHU: {href: "https://amzn.to/3nShe2Q",nameProduct: ``,image: '',summary: ``,slug: ""},
			B008DBRFBK: {href: "https://amzn.to/3utl0SP",nameProduct: ``,image: '',summary: ``,slug: ""},
			B073FMYZ3T: {href: "https://amzn.to/3eqCxFQ",nameProduct: ``,image: '',summary: ``,slug: ""},
			B01M0AGJIQ: {href: "https://amzn.to/33nIo8i",nameProduct: ``,image: '',summary: ``,slug: ""},
			B07LGDYV3C: {href: "https://amzn.to/3tpU8BG",nameProduct: ``,image: '',summary: ``,slug: ""},
			B00BTKAPUU: {href: "https://amzn.to/3xONyIt",nameProduct: ``,image: '',summary: ``,slug: ""},
			B07NWBXRNF: {href: "https://amzn.to/3eXFm02",nameProduct: ``,image: '',summary: ``,slug: ""},
			B07Q55RYK8: {href: "https://amzn.to/33ntoY4",nameProduct: ``,image: '',summary: ``,slug: ""},
			B00X7R1FZ2: {href: "https://amzn.to/2QYawfC",nameProduct: ``,image: '',summary: ``,slug: ""},
			B087CQVC9G: {href: "https://amzn.to/3tr1q8n",nameProduct: ``,image: '',summary: ``,slug: ""},
			B07BD2G4TY: {href: "https://amzn.to/3b8ndvv",nameProduct: ``,image: '',summary: ``,slug: ""},
			B00JIURCTA: {href: "https://amzn.to/33jDVUa",nameProduct: ``,image: '',summary: ``,slug: ""},
			B016J1ICDU: {href: "https://amzn.to/3nVZnba",nameProduct: ``,image: '',summary: ``,slug: ""},
			B07GZN3QNZ: {href: "https://amzn.to/3b8vQGf",nameProduct: ``,image: '',summary: ``,slug: ""},
			B01C9RIACG: {href: "https://amzn.to/3b6iLNu",nameProduct: ``,image: '',summary: ``,slug: ""},
			B07FFMTW8X: {href: "https://amzn.to/3enShJq",nameProduct: ``,image: '',summary: ``,slug: ""},
			B07LFJMS2S: {href: "https://amzn.to/3uDIbty",nameProduct: ``,image: '',summary: ``,slug: ""},
			B00LIAP2ZY: {href: "https://amzn.to/33k0wQn",nameProduct: ``,image: '',summary: ``,slug: ""},
			B0762N3T85: {href: "https://amzn.to/3xMryy5",nameProduct: ``,image: '',summary: ``,slug: ""},
			B01IRMBG7I: {href: "https://amzn.to/3epYCnJ",nameProduct: ``,image: '',summary: ``,slug: ""},
			B078MGY2CS: {href: "https://amzn.to/2Rr9Orf",nameProduct: ``,image: '',summary: ``,slug: ""},
			B00V3U5D6W: {href: "https://amzn.to/3tolo3x",nameProduct: ``,image: '',summary: ``,slug: ""},
			B01EGN8EXQ: {href: "https://amzn.to/3baYczM",nameProduct: ``,image: '',summary: ``,slug: ""},
			B01DTYAZO4: {href: "https://amzn.to/3vO926s",nameProduct: ``,image: '',summary: ``,slug: ""},
			B075XQRXCF: {href: "https://amzn.to/3bbg8tQ",nameProduct: ``,image: '',summary: ``,slug: ""},
			B01N5SMNJ4: {href: "https://amzn.to/2SmHAyf",nameProduct: ``,image: '',summary: ``,slug: ""},
			B01C6AASW6: {href: "https://amzn.to/3vL3ppI",nameProduct: ``,image: '',summary: ``,slug: ""},
			B06XFVQFP9: {href: "https://amzn.to/3epCsSJ",nameProduct: ``,image: '',summary: ``,slug: ""},
			B01KIMOEW4: {href: "https://amzn.to/33lZxPN",nameProduct: ``,image: '',summary: ``,slug: ""},
			B07HVSR8RF: {href: "https://amzn.to/3h6uSho",nameProduct: ``,image: '',summary: ``,slug: ""},
			B07B94ZR74: {href: "https://amzn.to/33jFKAu",nameProduct: ``,image: '',summary: ``,slug: ""},
			B000R50YZE: {href: "https://amzn.to/3tsO9MF",nameProduct: ``,image: '',summary: ``,slug: ""},
			B07B27ZP9T: {href: "https://amzn.to/3xUNib9",nameProduct: ``,image: '',summary: ``,slug: ""},
			B01I42EOGQ: {href: "https://amzn.to/3b8xUht",nameProduct: ``,image: '',summary: ``,slug: ""},
			B011LS47SA: {href: "https://amzn.to/3y1ezc3",nameProduct: ``,image: '',summary: ``,slug: ""},
			B01G7IKA1C: {href: "https://amzn.to/3nSC420",nameProduct: ``,image: '',summary: ``,slug: ""},
			B071VYD4WZ: {href: "https://amzn.to/33t9SJD",nameProduct: ``,image: '',summary: ``,slug: ""},
			B008UHXLGA: {href: "https://amzn.to/3b7Dy3A",nameProduct: ``,image: '',summary: ``,slug: ""},
			B07Q38HYF1: {href: "https://amzn.to/3tqbL4z",nameProduct: ``,image: '',summary: ``,slug: ""},
			B078WNSQS1: {href: "https://amzn.to/3tsfM8q",nameProduct: ``,image: '',summary: ``,slug: ""},
			B008RZFQKO: {href: "https://amzn.to/3tr4Jg3",nameProduct: ``,image: '',summary: ``,slug: ""},
			B0775YM1JC: {href: "https://amzn.to/33jwUmt",nameProduct: ``,image: '',summary: ``,slug: ""},
			B01AA8WOAK: {href: "https://amzn.to/2PWleD3",nameProduct: ``,image: '',summary: ``,slug: ""},
			B00USZPVXI: {href: "https://amzn.to/33nxcsk",nameProduct: ``,image: '',summary: ``,slug: ""},
			B01CS3JJ62: {href: "https://amzn.to/3b8psyE",nameProduct: ``,image: '',summary: ``,slug: ""},
			B0725VMPYD: {href: "https://amzn.to/2PWlqCh",nameProduct: ``,image: '',summary: ``,slug: ""},
			B07H84Q5HM: {href: "https://amzn.to/3nSD71W",nameProduct: ``,image: '',summary: ``,slug: ""},
			B0028AYQDC: {href: "https://amzn.to/3b8qpat",nameProduct: ``,image: '',summary: ``,slug: ""},
			B0016P3708: {href: "https://amzn.to/2PV0mMj",nameProduct: ``,image: '',summary: ``,slug: ""},
			B007NVSQEQ: {href: "https://amzn.to/3eX5Uyt",nameProduct: ``,image: '',summary: ``,slug: ""},
			B01E4RUUQI: {href: "https://amzn.to/3tkvjr2",nameProduct: ``,image: '',summary: ``,slug: ""},
			B000DZGN7Q: {href: "https://amzn.to/3tzj2PL",nameProduct: ``,image: '',summary: ``,slug: ""},
			B00F3S5U86: {href: "https://amzn.to/3h9A1p4",nameProduct: ``,image: '',summary: ``,slug: ""},
			B00KW4PO82: {href: "https://amzn.to/3xUPuiE",nameProduct: ``,image: '',summary: ``,slug: ""},
			B00Q8M0NWE: {href: "https://amzn.to/3xU24yz",nameProduct: ``,image: '',summary: ``,slug: ""},
			B083G9WVNC: {href: "https://amzn.to/33nxHTe",nameProduct: ``,image: '',summary: ``,slug: ""},
			B073BLHCND: {href: "https://amzn.to/3h89Lvh",nameProduct: ``,image: '',summary: ``,slug: ""},
			B01KUBW1XC: {href: "https://amzn.to/3eqEHoN",nameProduct: ``,image: '',summary: ``,slug: ""},
			B07D8QGJ5V: {href: "https://amzn.to/3uqtpXj",nameProduct: ``,image: '',summary: ``,slug: ""},
			B077416M4M: {href: "https://amzn.to/3eZ9LLs",nameProduct: ``,image: '',summary: ``,slug: ""},
			B0016J9RUI: {href: "https://amzn.to/3vLTqR1",nameProduct: ``,image: '',summary: ``,slug: ""},
			B002VWK1TA: {href: "https://amzn.to/3h9AlUO",nameProduct: ``,image: '',summary: ``,slug: ""}
		}
	}
	return dataAMZ;
}
